# Generated by Django 6.1.1 on 2026-09-21 06:39

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(storage=accounts.models.private_storage, upload_to=accounts.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), accounts.models.validate_cv_size])),
                ('original_filename', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='accounts.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'CV',
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('profile',), name='one_default_cv_per_profile')],
            },
        ),
    ]
