# Generated by Django 6.0.4 on 2026-09-21 08:02

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill_education_experience_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional. JPG, PNG or WebP, up to 2 MB.', upload_to=accounts.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_logo_size]),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='verification_document',
            field=models.FileField(blank=True, help_text='PDF or image, up to 10 MB. Kept private.', storage=accounts.models.private_verification_storage, upload_to=accounts.models.verification_doc_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), accounts.models.validate_verification_doc_size]),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
